### ISSUE TITLE
something going wrong with updating webppl and wp-editor

### ISSUE THREAD

**Issue by owainevans** [agentmodels/agentmodels.org#11]
the update is taking an extremely long time for each (longer than before). on my local jekyll serve, after update, i get "hasProperties" not found. this function is in src/gridworld.wppl. it seems that it's order has been changed in the minified js. so maybe something is going wrong with minification?

**Comment by stuhlmueller** [comment]
Try upgrading `npm`:

```
npm install -g npm
```

This resolved the issue for me.

I think there was a version of `npm` that was overly aggressive in sorting dependencies, which resulted in the `wppl` entry in our `package.json` getting sorted, which caused errors due to the order dependence of the definitions in the `.wppl` files.
