### ISSUE TITLE
Add page for interactive editor with bundled packages

### ISSUE THREAD

**Issue by stuhlmueller** [agentmodels/agentmodels.org#37]

**Comment by russellcthomas** [comment]
Thanks.  How soon do you think this will be completed?

**Comment by stuhlmueller** [comment]
I just added a basic version. Let me know if you run into any problems!

**Comment by russellcameronthomas** [comment]
Thanks!  I did a quick test at it worked. I'll let you know if there are problems.

I presume when a user creates a "New File" that it is stored locally in the browser cache, and that it disappears if the browser cache is cleared. True? And is it also true that the only way to save a local copy is to copy/paste the .md window into a .txt or .md file?

If so, then I may have to clone agentmodeling.org and host it on my own github so I can have my own home directory and pages that all class participants can see & access, rather than rely on "New Files" I create in this interactive editor (which only I see/access).
